<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>WorkbenchConnect</AssemblyName>
    <RootNamespace>WorkbenchConnect</RootNamespace>
    <LangVersion>latest</LangVersion>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../../Assemblies/</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" PrivateAssets="All" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2" PrivateAssets="All" />
  </ItemGroup>

</Project>
